data_collection_task:
  description: >
    Collect comprehensive data about {topic} from various reliable sources.
    Focus on gathering recent and relevant information, considering the current year is 2024.
    Include technical specifications, market data, and industry trends where applicable.
  expected_output: >
    A structured dataset containing key information about {topic}, including sources,
    timestamps, and relevance indicators.
  agent: scraper_agent

analysis_task:
  description: >
    Perform a detailed analysis of the collected {topic} data.
    Identify patterns, trends, and correlations.
    Generate insights about market position, technical aspects, and potential opportunities.
  expected_output: >
    A comprehensive analysis report including:
    - Key trends and patterns
    - Statistical analysis
    - Data visualizations
    - Identified opportunities and challenges
  agent: analyse_agent

optimization_task:
  description: >
    Based on the analysis results, develop optimization strategies for {topic}.
    Propose concrete improvements and solutions.
    Include implementation recommendations and expected outcomes.
  expected_output: >
    A detailed optimization plan including:
    - Specific improvement recommendations
    - Implementation steps
    - Expected benefits and ROI
    - Risk assessment and mitigation strategies
  agent: optimization_agent
